### ISSUE TITLE
[Request Improve] Check key validate

### ISSUE THREAD

**Issue by koir1100** [SeunMatt/request-validator#4]
Hello, Thank you for your library to validate json.

By the way, I want to check that key(s) are also check validate elements.
For example, 

```
{
    "preferences1": {
        "emailNotificationEnabled": true,
        "frequency": 4
    },
    "preferences2": {
        "emailNotificationEnabled": true,
        "frequency": 4
    }
}
```

I want to check keys "preferences1", "preferences2" are exist or not exist.
if conditions are satisfied, and then check validate each values.

Please understand expression even if it's awkward. Thank you in advanced.

**Comment by SeunMatt** [comment]
Hello @koir1100 

I believe what you're looking for is the `optional` rule. I have added it to the rule list table [here](https://github.com/SeunMatt/request-validator#validation-rules) 

I also used it as an example in number 3 of the `How it works` section in the README [https://github.com/SeunMatt/request-validator#how-it-works](https://github.com/SeunMatt/request-validator#how-it-works) 

I forgot to add it explicitly to the rule list before which I think might have caused the confusion.  Apologies for that. 

Let me know if it works as you expect. 

Regards
